packages:
    - apps/*
    - packages/*

catalog:
    '@biomejs/biome': 2.5.12
    '@types/node': ^26.5.0
    typescript: ^5.9.3
    zod: ^4.5.4
    express: ^5.0.6
    vitest: ^5.0.0
    react: ^19.2.0
    react-dom: ^19.2.0
